region_access:
  ipaddress: 'REGION IP ADDRESS'
  cloud_domain: 'USER TENANT/DOMAIN'
  cloud_user: 'USER NAME'
  cloud_password: 'USER PASSWORD'
  cloud_admin_password: 'CLOUD ADMIN PASSWORD'
  project: 'USER PROJECT'
purestoragearray:
  ipaddress: 'PURE STORAGE IP ADDRESS'
  apitoken: 'PURE STORAGE API TOKEN'
region_access_replicasite:
  ipaddress: 'REGION IP ADDRESS - REPLICA SITE'
  cloud_domain: 'USER TENANT/DOMAIN - REPLICA SITE'
  cloud_user: 'USER NAME - REPLICA SITE'
  cloud_password: 'USER PASSWORD - REPLICA SITE'
  cloud_admin_password: 'CLOUD ADMIN PASSWORD - REPLICA SITE'
  project: 'USER PROJECT - REPLICA SITE'
purestoragearray_replicasite:
  ipaddress: 'PURE STORAGE IP ADDRESS - REPLICA SITE'
  apitoken: 'PURE STORAGE API TOKEN - REPLICA SITE'
settings:
   historical_records: '4'
